spring.application.name=AcedemyManager

server.port=9000

# User/pass de la base de datos
spring.datasource.username=sa
spring.datasource.password=

# Le indicamos a JPA/Hibernate que se encargue de generar el DDL
spring.jpa.hibernate.ddl-auto=create-drop

# Habilitamos la consola de H2
# http://localhost:{server.port}/h2-console
# En nuestro caso http://localhost:9000/h2-console
spring.h2.console.enabled=true

spring.jpa.show-sql=true
